### ISSUE TITLE
use golang.org/x/tools/benchmark/parse

### ISSUE THREAD

**Issue by josharian** [CodingBerg/benchgraph#1]
Nice work.

You might find the [golang.org/x/tools/benchmark/parse](https://godoc.org/golang.org/x/tools/benchmark/parse) package useful. Or not, since you have everything working now. :)

**Comment by codingberg** [comment]
I'm already using ParseLine() from that package. The next parse iteration is within benchmark name, which is custom implemented. Thank you.
